#!/usr/bin/env bash

# Define the Wi-Fi interface
INTERFACE="${INTERFACE:-wlo1}"
# same
# Define colors
COLOR_GE80=${COLOR_GE80:-#00FF00}
COLOR_GE60=${COLOR_GE60:-#FFF600}
COLOR_GE40=${COLOR_GE40:-#FFAE00}
COLOR_LOWR=${COLOR_LOWR:-#FF0000}
COLOR_DOWN=${COLOR_DOWN:-#FF0000}

# Check if wireless directory exists
if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
  echo "Wireless interface not found"
  exit 1
fi

# Check if the interface is down
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
  echo "down"
  echo "down"
  echo $COLOR_DOWN
  exit 1
fi

# Get the Wi-Fi quality
QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

# Check if the command was successful
if [[ $? -ne 0 ]]; then
  echo "Error obtaining Wi-Fi quality"
  exit 1
fi

# Print the quality and color
echo $QUALITY% # full text
echo $QUALITY% # short text

if [[ $QUALITY -ge 80 ]]; then
  echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
  echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
  echo $COLOR_GE40
else
  echo $COLOR_LOWR
fi
